SB.register('science',[
SB.topic('variables','Pemboleh ubah & inferens','DIUBAH → Dimanipulasikan. DIUKUR / DIPERHATI → Bergerak balas. DIKEKALKAN SAMA → Dimalarkan. SEBAB SAINTIFIK → Inferens.','Contoh: Jenis permukaan diubah, jarak kereta diukur, kereta yang sama digunakan. Jangan tulis keputusan apabila soalan meminta sebab.'),
SB.topic('kps','Pemerhatian, ramalan & hubungan','Pemerhatian berdasarkan apa yang diukur atau dilihat. Inferens ialah sebab saintifik. Ramalan mestilah disokong corak data.','Contoh: Bilangan pernafasan meningkat selepas berlari (pemerhatian). Badan memerlukan lebih oksigen (inferens).'),
SB.topic('manusia','Manusia & haiwan','Paru-paru ialah organ pernafasan manusia. Kadar pernafasan boleh berubah mengikut aktiviti. Perkumuhan menyingkir bahan buangan badan.','Contoh: Aktiviti lebih cergas biasanya meningkatkan kadar pernafasan. Haiwan bernafas melalui organ yang berlainan.'),
SB.topic('tumbuhan','Tumbuhan','Tumbuhan bergerak balas terhadap cahaya, air, graviti dan sentuhan. Tumbuhan memerlukan cahaya, air dan karbon dioksida untuk fotosintesis.','Contoh: Pucuk tumbuh ke arah cahaya; akar tumbuh ke arah air.'),
SB.topic('cahaya','Cahaya & bunyi','Cahaya bergerak lurus, boleh dipantulkan dan dibiaskan. Bunyi terhasil melalui getaran. Saiz bayang-bayang berubah apabila kedudukan sumber cahaya berubah.','Contoh: Pensel kelihatan bengkok dalam air kerana pembiasan cahaya.'),
SB.topic('tenaga','Tenaga','Tenaga boleh berubah bentuk. Kenal pasti sumber tenaga dan perubahan yang berlaku pada alat harian.','Contoh: Lampu suluh: tenaga kimia → tenaga elektrik → tenaga cahaya dan haba.'),
SB.topic('bahan','Sifat bahan','Bahan mempunyai sifat seperti menyerap air, kalis air, menghantar elektrik dan membenarkan cahaya melaluinya. Pilih bahan mengikut kegunaan.','Contoh: Bahan kalis air sesuai untuk baju hujan.'),
SB.topic('bumi','Bumi, Bulan & Matahari','Putaran Bumi menyebabkan siang dan malam. Kedudukan Bulan dan cahaya Matahari mempengaruhi rupa Bulan yang kelihatan.','Contoh: Bahagian Bumi yang menghadap Matahari mengalami siang.'),
SB.topic('mesin','Mesin ringkas','Tuas mempunyai fulkrum, beban dan daya. Mesin ringkas membantu memudahkan kerja.','Contoh: Kedudukan fulkrum yang sesuai dapat mengurangkan daya untuk mengangkat beban.')]);
const experiments=[
['Air & anak pokok','tumbuhan','Aina menyiram tiga anak pokok kacang dengan 10 ml, 30 ml dan 50 ml air setiap hari. Jenis pokok, tanah dan tempoh pemerhatian adalah sama. Tinggi pokok selepas tujuh hari dicatat.','Jumlah air','Tinggi anak pokok','Jenis anak pokok','Pokok yang kurang air tumbuh lebih rendah kerana air diperlukan untuk pertumbuhan.',['Air / Water (ml)','Tinggi / Height (cm)'],[[10,5],[30,11],[50,15]],['air','jumlah air','isi padu air'],['tinggi','ketinggian'],['jenis pokok','jenis anak pokok','jenis tumbuhan','biji benih'],[['kurang air','kekurangan air','tidak mendapat air'],['pertumbuhan','tumbuh','membesar']], 'plants'],
['Aktiviti & pernafasan','manusia','Haris mengira pernafasannya selama satu minit selepas duduk, berjalan dan berlari. Orang dan tempoh kiraan adalah sama bagi setiap aktiviti.','Jenis aktiviti','Bilangan pernafasan seminit','Orang yang sama','Berlari memerlukan lebih banyak oksigen, maka kadar pernafasan meningkat.',['Aktiviti / Activity','Pernafasan / Breaths per min'],[['Duduk',18],['Berjalan',25],['Berlari',36]],['jenis aktiviti','aktiviti'],['bilangan pernafasan','kadar pernafasan','pernafasan seminit'],['orang yang sama','orang','individu','tempoh kiraan'],[['lebih banyak oksigen','banyak oksigen','more oxygen'],['berlari','aktiviti cergas','running']],'breathing'],
['Jarak lampu & bayang-bayang','cahaya','Mira mengubah jarak lampu suluh daripada bola pada 10 cm, 20 cm dan 30 cm. Bola dan jarak bola ke skrin dikekalkan. Tinggi bayang-bayang diukur.','Jarak lampu daripada bola','Tinggi bayang-bayang','Jarak bola ke skrin','Lampu yang lebih dekat menghasilkan bayang-bayang lebih besar kerana cahaya yang dihalang merebak lebih luas.',['Jarak / Distance (cm)','Tinggi bayang / Shadow height (cm)'],[[10,18],[20,12],[30,9]],['jarak lampu','jarak sumber cahaya'],['tinggi bayang','saiz bayang'],['jarak bola ke skrin','jarak objek ke skrin','bola yang sama','saiz bola'],[['lebih dekat','jarak dekat'],['lebih besar','besar','luas']],'shadow'],
['Jenis bahan & serapan','bahan','Danial menitis 10 ml air pada kain kapas, plastik dan tisu yang sama luas. Air yang diserap selepas satu minit diukur.','Jenis bahan','Isi padu air yang diserap','Luas bahan','Tisu menyerap lebih banyak air kerana mempunyai sifat menyerap air.',['Bahan / Material','Air diserap / Absorbed (ml)'],[['Kapas',6],['Plastik',0],['Tisu',9]],['jenis bahan','bahan'],['air yang diserap','isi padu air diserap','jumlah air diserap'],['luas bahan','saiz bahan','jumlah air','10 ml','tempoh masa'],[['menyerap air','serap air'],['tisu']],'materials'],
['Jarak bunyi','cahaya','Sofea mendengar loceng yang sama pada jarak 1 m, 3 m dan 5 m. Kekuatan loceng dan tempat penyiasatan dikekalkan. Tahap kelantangan bunyi diperhatikan.','Jarak dari loceng','Kelantangan bunyi','Loceng yang sama','Bunyi lebih perlahan apabila pendengar berada lebih jauh daripada sumber bunyi.',['Jarak / Distance (m)','Bunyi / Loudness'],[[1,'Kuat'],[3,'Sederhana'],[5,'Perlahan']],['jarak','jarak dari loceng'],['kelantangan','bunyi','kekuatan bunyi'],['loceng yang sama','loceng','kekuatan loceng','tempat'],[['lebih jauh','jauh'],['perlahan','lemah']],'sound'],
['Permukaan & pantulan','cahaya','Iman menyuluh cahaya pada cermin, kadbod dan kain dengan lampu serta sudut yang sama. Kejelasan pantulan diperhatikan.','Jenis permukaan','Kejelasan pantulan','Sudut cahaya','Cermin memantulkan cahaya dengan baik kerana permukaannya licin dan berkilat.',['Permukaan / Surface','Pantulan / Reflection'],[['Cermin','Jelas'],['Kadbod','Kurang jelas'],['Kain','Tidak jelas']],['jenis permukaan','permukaan','bahan permukaan'],['kejelasan pantulan','pantulan'],['sudut cahaya','lampu yang sama','lampu','sudut'],[['licin','smooth'],['berkilat','shiny']],'reflection'],
['Bahan & cahaya','bahan','Ravi menyuluh bahan kaca jernih, kertas nipis dan kayu. Lampu serta jarak dikekalkan. Jumlah cahaya yang menembusi bahan diperhatikan.','Jenis bahan','Cahaya yang menembusi bahan','Jarak lampu ke bahan','Kayu menghalang cahaya kerana kayu ialah bahan legap.',['Bahan / Material','Cahaya / Light'],[['Kaca jernih','Semua'],['Kertas nipis','Sebahagian'],['Kayu','Tiada']],['jenis bahan','bahan'],['cahaya yang menembusi','jumlah cahaya','cahaya melalui'],['jarak','lampu yang sama','lampu'],[['kayu'],['legap','menghalang cahaya','tidak membenarkan cahaya']],'transparency'],
['Cahaya & pucuk','tumbuhan','Lina meletakkan dua anak pokok yang sama dalam kotak berlubang. Lubang kotak P di kiri dan Q di kanan. Air dan tempoh pemerhatian sama. Arah pucuk dicatat.','Kedudukan sumber cahaya','Arah pertumbuhan pucuk','Jumlah air','Pucuk tumbuh ke arah cahaya kerana tumbuhan bergerak balas terhadap cahaya.',['Kotak / Box','Arah pucuk / Shoot direction'],[['P: lubang kiri','Ke kiri'],['Q: lubang kanan','Ke kanan']],['kedudukan cahaya','kedudukan sumber cahaya','arah cahaya'],['arah pucuk','arah pertumbuhan pucuk','arah pertumbuhan'],['jumlah air','jenis pokok','tempoh masa'],[['cahaya'],['bergerak balas','ke arah cahaya']],'plants'],
['Air & akar','tumbuhan','Zaki meletakkan air pada sebelah kiri dan kanan dua bekas anak pokok yang sama. Jenis benih dan cahaya dikekalkan. Arah akar diperhatikan.','Kedudukan air','Arah pertumbuhan akar','Jenis biji benih','Akar tumbuh ke arah air kerana akar bergerak balas terhadap air.',['Bekas / Container','Arah akar / Root direction'],[['P: air kiri','Ke kiri'],['Q: air kanan','Ke kanan']],['kedudukan air','arah air'],['arah akar','arah pertumbuhan akar'],['jenis benih','jenis biji benih','cahaya','anak pokok'],[['air'],['bergerak balas','ke arah air']],'plants'],
['Tempoh aktiviti & pernafasan','manusia','Mei berlari selama 1 minit, 2 minit dan 3 minit dalam cubaan berasingan selepas berehat. Orang, jenis aktiviti dan tempoh kiraan pernafasan dikekalkan.','Tempoh aktiviti','Kadar pernafasan','Jenis aktiviti','Aktiviti yang lebih lama memerlukan lebih banyak oksigen untuk badan.',['Masa / Duration (min)','Pernafasan seminit'],[[1,24],[2,30],[3,36]],['tempoh aktiviti','masa aktiviti','tempoh berlari'],['kadar pernafasan','bilangan pernafasan'],['jenis aktiviti','orang yang sama','tempoh kiraan'],[['oksigen'],['lebih banyak','meningkat','bertambah']],'breathing'],
['Bahan & penebat elektrik','bahan','Aina menguji sudu logam, kayu dan plastik dalam litar penguji yang sama. Bateri, mentol serta sambungan lain dikekalkan. Keadaan mentol diperhatikan.','Jenis bahan','Keadaan mentol','Bilangan bateri','Mentol menyala dengan sudu logam kerana logam boleh menghantar arus elektrik.',['Bahan / Material','Mentol / Bulb'],[['Logam','Menyala'],['Kayu','Tidak menyala'],['Plastik','Tidak menyala']],['jenis bahan','bahan'],['keadaan mentol','mentol menyala','nyalaan mentol'],['bilangan bateri','bateri','mentol yang sama','litar'],[['logam'],['menghantar elektrik','konduktor','menghantar arus']],'circuit'],
['Bahan & terapung','bahan','Haris memasukkan gabus, batu dan duit syiling dalam bekas air yang sama. Saiz bekas dan isi padu air dikekalkan. Kedudukan bahan dicatat.','Jenis bahan','Kedudukan bahan dalam air','Isi padu air','Gabus terapung kerana ketumpatannya lebih rendah daripada air.',['Bahan / Material','Keadaan / Observation'],[['Gabus','Terapung'],['Batu','Tenggelam'],['Syiling','Tenggelam']],['jenis bahan','bahan'],['terapung atau tenggelam','kedudukan bahan','keadaan bahan'],['isi padu air','jumlah air','bekas'],[['gabus'],['kurang tumpat','ketumpatan lebih rendah']],'floating'],
['Fulkrum & daya','mesin','Mira menggunakan pembaris sebagai tuas untuk mengangkat pemadam yang sama. Jarak fulkrum dari beban diubah. Daya yang diperlukan dibandingkan.','Jarak fulkrum dari beban','Daya yang diperlukan','Beban yang sama','Fulkrum lebih dekat kepada beban membolehkan beban diangkat dengan daya lebih kecil.',['Jarak / Distance (cm)','Daya / Force'],[[2,'Kecil'],[4,'Sederhana'],[6,'Besar']],['jarak fulkrum','kedudukan fulkrum'],['daya','daya yang diperlukan'],['beban','pemadam','pembaris yang sama'],[['fulkrum dekat','dekat kepada beban','lebih dekat'],['daya kecil','daya lebih kecil','kurang daya']],'lever'],
['Permukaan gelap & cahaya','cahaya','Danial menguji kadbod putih, cermin dan kain hitam dengan lampu yang sama. Jarak lampu dikekalkan. Tahap cahaya pantulan dibandingkan.','Jenis permukaan','Tahap cahaya pantulan','Jarak lampu','Cermin menghasilkan pantulan lebih kuat kerana permukaannya licin dan berkilat.',['Permukaan','Pantulan'],[['Kadbod putih','Sederhana'],['Cermin','Kuat'],['Kain hitam','Lemah']],['jenis permukaan','permukaan'],['cahaya pantulan','tahap pantulan','kekuatan pantulan'],['jarak lampu','lampu'],[['licin'],['berkilat']],'reflection'],
['Sentuhan & daun','tumbuhan','Sofea menyentuh daun semalu P dan tidak menyentuh daun Q. Jenis tumbuhan serta tempat sama. Keadaan daun selepas beberapa saat dicatat.','Sentuhan pada daun','Keadaan daun','Jenis tumbuhan','Daun semalu menguncup kerana bergerak balas terhadap sentuhan.',['Daun / Leaf','Keadaan / Observation'],[['P: disentuh','Menguncup'],['Q: tidak disentuh','Terbuka']],['sentuhan','daun disentuh','menyentuh daun'],['keadaan daun','daun menguncup'],['jenis tumbuhan','semalu','tempat'],[['sentuhan'],['bergerak balas','menguncup']],'leaves'],
['Ketegangan getah & bunyi','cahaya','Iman memetik gelang getah yang sama pada tiga tahap ketegangan. Cara petikan sama. Kelangsingan bunyi dibandingkan.','Ketegangan gelang getah','Kelangsingan bunyi','Jenis gelang getah','Getah lebih tegang bergetar lebih cepat lalu menghasilkan bunyi lebih nyaring.',['Ketegangan','Bunyi'],[['Rendah','Rendah'],['Sederhana','Sederhana'],['Tinggi','Nyaring']],['ketegangan','ketegangan getah'],['kelangsingan','bunyi nyaring','kelangsingan bunyi'],['gelang getah yang sama','jenis getah','cara petikan'],[['bergetar lebih cepat','getaran cepat'],['nyaring','tinggi']],'sound'],
['Kekuatan tiupan & bunyi','cahaya','Ravi meniup wisel yang sama dengan perlahan, sederhana dan kuat. Jarak pendengar dikekalkan. Kelantangan bunyi dicatat.','Kekuatan tiupan','Kelantangan bunyi','Wisel yang sama','Tiupan lebih kuat menghasilkan getaran lebih kuat lalu bunyi lebih kuat.',['Tiupan','Kelantangan'],[['Perlahan','Perlahan'],['Sederhana','Sederhana'],['Kuat','Kuat']],['kekuatan tiupan','tiupan'],['kelantangan','kekuatan bunyi'],['wisel','jarak pendengar'],[['getaran'],['lebih kuat','kuat']],'sound'],
['Air & pembiasan','cahaya','Lina memerhati pensel dalam bekas kosong P dan bekas berair Q. Pensel, bekas dan sudut pandangan adalah sama. Rupa pensel dicatat.','Kehadiran air','Rupa pensel','Pensel yang sama','Pensel kelihatan bengkok dalam air kerana cahaya dibiaskan apabila melalui air dan udara.',['Bekas','Rupa pensel'],[['P: tiada air','Lurus'],['Q: ada air','Kelihatan bengkok']],['kehadiran air','ada air','air'],['rupa pensel','pensel bengkok','keadaan pensel'],['pensel yang sama','bekas','sudut pandangan'],[['cahaya'],['dibiaskan','pembiasan']],'refraction'],
['Saiz objek & bayang','cahaya','Zaki menggunakan tiga kad bulatan bersaiz kecil, sederhana dan besar. Kedudukan lampu serta skrin dikekalkan. Saiz bayang-bayang dicatat.','Saiz objek','Saiz bayang-bayang','Jarak lampu ke objek','Objek lebih besar menghalang lebih banyak cahaya lalu menghasilkan bayang lebih besar.',['Objek','Bayang'],[['Kecil','Kecil'],['Sederhana','Sederhana'],['Besar','Besar']],['saiz objek','saiz kad'],['saiz bayang','bayang-bayang'],['jarak lampu','jarak skrin','lampu yang sama'],[['menghalang cahaya','halang cahaya'],['lebih banyak','banyak']],'shadow'],
['Kalis air','bahan','Mei menuang 20 ml air pada kain kapas, kertas dan plastik. Luas bahan serta tempoh pemerhatian dikekalkan. Kebocoran air ke bekas bawah dicatat.','Jenis bahan','Air yang bocor','Luas bahan','Plastik tidak membenarkan air melaluinya kerana plastik kalis air.',['Bahan','Air di bawah (ml)'],[['Kapas',12],['Kertas',8],['Plastik',0]],['jenis bahan','bahan'],['air yang bocor','kebocoran air','jumlah air bocor'],['luas bahan','jumlah air','tempoh masa'],[['plastik'],['kalis air','tidak membenarkan air']],'materials']
];
SB.experiments=experiments;
experiments.forEach((e,i)=>{let common={topic:'variables',stem:e[2],en:'Read the investigation diagram and results. Identify the variables and give a scientific reason.',diagram:{type:'experiment',kind:e[13],title:e[0],headers:e[7],rows:e[8]},hints:['DIUBAH, DIUKUR, DIKEKALKAN — padankan setiap perkara dalam situasi.','Cari apa yang berbeza antara cubaan. Kemudian cari hasil yang dicatat.','Contoh lain: masa bersenam diubah, peluh diperhatikan, orang yang sama dikekalkan. Inferens menerangkan sebab saintifik.'],explanation:`Dimanipulasikan: ${e[3]}. Bergerak balas: ${e[4]}. Dimalarkan: ${e[5]}. Inferens: ${e[6]}`};
SB.add('science',{...common,id:'sc-v-'+i,parts:[SB.concept('(a) Pemboleh ubah dimanipulasikan / Manipulated variable',e[3],[e[9]],2),SB.concept('(b) Pemboleh ubah bergerak balas / Responding variable',e[4],[e[10]],2),SB.concept('(c) Pemboleh ubah dimalarkan / Constant variable',e[5],[e[11]],2),SB.concept('(d) Nyatakan inferens / State an inference',e[6],e[12],2)]});
const skills=[['pemerhatian','Nyatakan satu pemerhatian berdasarkan jadual. / State an observation.',`${e[8][0][0]} menghasilkan ${e[8][0][1]}.`,[[String(e[8][0][0])],[String(e[8][0][1])]]],['tujuan','Nyatakan tujuan penyiasatan. / State the aim.',`Untuk menyiasat kesan ${e[3].toLowerCase()} terhadap ${e[4].toLowerCase()}.`,[e[9],e[10]]],['ujian-adil','Nyatakan satu perkara yang perlu dikekalkan untuk ujian adil. / Name a factor to keep constant.',e[5],[e[11]]],['hubungan','Nyatakan hubungan atau perbezaan berdasarkan data. / State the relationship or difference.',`${e[8][0][0]}: ${e[8][0][1]}; ${e[8][e[8].length-1][0]}: ${e[8][e[8].length-1][1]}.`,[[String(e[8][0][1])],[String(e[8][e[8].length-1][1])]]]];
skills.forEach((s,j)=>SB.add('science',{...common,id:`sc-k-${i}-${j}`,topic:j===2?e[1]:'kps',parts:[SB.concept(s[1],s[2],s[3],2)],explanation:s[2]+' Jawapan lain yang disokong data boleh disemak ibu bapa.'}));});
const facts=[
['manusia','Apakah organ pernafasan manusia?','What is the human breathing organ?',['Paru-paru','Jantung','Perut','Ginjal'],0,'lungs','Paru-paru digunakan untuk pertukaran gas.'],
['manusia','Aktiviti manakah biasanya menghasilkan kadar pernafasan paling tinggi?','Which activity usually produces the highest breathing rate?',['Duduk','Tidur','Berlari','Membaca'],2,'activity','Aktiviti cergas memerlukan lebih banyak oksigen.'],
['manusia','Bahan buangan manakah dikeluarkan melalui kulit?','Which waste is excreted through the skin?',['Peluh','Najis','Air liur','Darah'],0,'skin','Kulit mengeluarkan peluh melalui proses perkumuhan.'],
['manusia','Ikan bernafas menggunakan…','Fish breathe using…',['Paru-paru','Insang','Spirakel','Kulit sahaja'],1,'fish','Insang membantu ikan mendapatkan oksigen terlarut dalam air.'],
['tumbuhan','Pucuk tumbuhan biasanya bergerak balas ke arah…','Shoots usually respond towards…',['Bunyi','Cahaya','Batu','Udara panas'],1,'plants','Pucuk bergerak balas terhadap cahaya.'],
['tumbuhan','Apakah hasil fotosintesis?','Which is produced by photosynthesis?',['Makanan dan oksigen','Air dan tanah','Asap dan haba','Batu dan pasir'],0,'leaves','Fotosintesis menghasilkan makanan dan oksigen.'],
['cahaya','Pensel kelihatan bengkok apabila dimasukkan ke dalam air kerana…','A pencil looks bent in water because of…',['Pantulan','Pembiasan','Getaran','Penyerapan air'],1,'refraction','Cahaya dibiaskan apabila melalui medium berlainan.'],
['cahaya','Bunyi terhasil apabila objek…','Sound is produced when an object…',['Membeku','Bergetar','Membesar','Mencair'],1,'sound','Getaran menghasilkan bunyi.'],
['bahan','Bahan manakah paling sesuai untuk baju hujan?','Which material is most suitable for a raincoat?',['Tisu','Kertas','Kain kapas','Plastik kalis air'],3,'materials','Baju hujan memerlukan bahan yang tidak membenarkan air melaluinya.'],
['tenaga','Apakah perubahan tenaga utama pada kipas elektrik?','What is the main energy change in an electric fan?',['Elektrik → kinetik','Bunyi → kimia','Cahaya → elektrik','Kinetik → kimia'],0,'fan','Tenaga elektrik menggerakkan bilah kipas.'],
['manusia','Apakah organ pernafasan belalang?','What is the breathing organ of a grasshopper?',['Insang','Paru-paru','Spirakel','Akar'],2,'insect','Serangga bernafas melalui spirakel, bukan melalui kepala.'],
['manusia','Apakah maksud penyahtinjaan?','What is defecation?',['Mengeluarkan peluh','Mengeluarkan najis','Mengambil oksigen','Mengeluarkan air mata'],1,'human','Penyahtinjaan menyingkir sisa makanan sebagai najis.'],
['tumbuhan','Daun semalu menguncup apabila disentuh. Ini ialah gerak balas terhadap…','A mimosa leaf closes when touched. It responds to…',['Cahaya','Air','Graviti','Sentuhan'],3,'leaves','Sentuhan merangsang daun semalu untuk menguncup.'],
['tumbuhan','Bahagian tumbuhan manakah menyerap air?','Which plant part absorbs water?',['Bunga','Akar','Buah','Pucuk'],1,'plants','Akar menyerap air daripada tanah.'],
['cahaya','Bayang-bayang terbentuk apabila cahaya dihalang oleh bahan…','A shadow forms when light is blocked by an…',['Lutsinar','Legap','Lut sinar','Cair'],1,'shadow','Bahan legap menghalang cahaya.'],
['cahaya','Permukaan manakah memantulkan cahaya dengan paling jelas?','Which surface reflects light most clearly?',['Kain','Kadbod','Cermin','Tanah'],2,'reflection','Cermin yang licin dan berkilat menghasilkan pantulan jelas.'],
['tenaga','Sumber tenaga manakah boleh diperbaharui?','Which energy source is renewable?',['Petroleum','Arang batu','Gas asli','Angin'],3,'wind','Angin ialah sumber boleh diperbaharui.'],
['bahan','Mengapakah tuala diperbuat daripada bahan penyerap air?','Why is a towel made from absorbent material?',['Untuk mengeringkan badan','Untuk menghasilkan cahaya','Untuk terapung','Untuk menghalang bunyi'],0,'materials','Tuala perlu menyerap air pada badan.'],
['bumi','Apakah yang menyebabkan siang dan malam?','What causes day and night?',['Putaran Bumi','Putaran Bulan sahaja','Hujan','Awan bergerak'],0,'earth','Bahagian Bumi menghadap Matahari mengalami siang; bahagian bertentangan malam.'],
['mesin','Apakah nama titik sokongan pada tuas?','What is the support point of a lever called?',['Beban','Daya','Fulkrum','Permukaan'],2,'lever','Tuas bergerak atau berputar pada fulkrum.']
];
facts.forEach((f,i)=>SB.add('science',{id:'sc-f-'+i,topic:f[0],stem:f[1],en:f[2],diagram:{type:'science',kind:f[5]},parts:[SB.mcq('Pilih jawapan / Choose an answer',f[3],f[4])],hints:['Kenal pasti konsep yang ditanya dalam rajah.','Bezakan fungsi atau sifat setiap pilihan.','Contoh lain: apabila diminta organ, jawab bahagian badan; apabila diminta proses, jawab nama proses.'],explanation:f[6]}));
// Latihan aplikasi dengan pelbagai bentuk (padanan, pilihan sifat, urutan dan respons pendek).
const applications=[
['manusia','Padankan haiwan dengan organ pernafasannya.','Match the animals to their breathing organs.','animals',[SB.text('Ikan / Fish','Insang',1,['gills']),SB.text('Burung / Bird','Paru-paru',1,['lungs']),SB.text('Belalang / Grasshopper','Spirakel',1,['spiracles']),SB.text('Cacing / Earthworm','Kulit lembap',1,['kulit','moist skin'])],'Ikan: insang; burung: paru-paru; belalang: spirakel; cacing: kulit lembap.'],
['tumbuhan','Lengkapkan keperluan fotosintesis berdasarkan rajah.','Complete the requirements for photosynthesis.','photosynthesis',[SB.text('Sumber tenaga / Energy source','Cahaya matahari',1,['cahaya','sunlight']),SB.text('Diserap akar / Absorbed by roots','Air',1,['water']),SB.text('Gas diperlukan / Gas required','Karbon dioksida',1,['carbon dioxide']),SB.text('Gas dihasilkan / Gas produced','Oksigen',1,['oxygen'])],'Cahaya, air dan karbon dioksida diperlukan; oksigen dihasilkan.'],
['bahan','Kelaskan bahan mengikut keupayaan membenarkan cahaya melaluinya.','Classify materials by light transmission.','transparency',[SB.text('Kaca jernih','Lutsinar',1,['transparent']),SB.text('Kertas nipis','Lut sinar',1,['translucent','lutsinar sebahagian']),SB.text('Kayu','Legap',1,['opaque']),SB.text('Bahan paling sesuai untuk tingkap / Window material','Kaca jernih',1,['kaca','glass'])],'Kaca jernih: lutsinar; kertas nipis: lut sinar; kayu: legap.'],
['mesin','Kenal pasti komponen tuas dan kegunaannya.','Identify the parts of the lever.','lever',[SB.text('Titik sokongan / Support point','Fulkrum',1,['fulcrum']),SB.text('Objek yang diangkat / Object lifted','Beban',1,['load']),SB.text('Tolakan atau tarikan / Push or pull','Daya',1,['effort','force']),SB.text('Contoh alat menggunakan tuas / Example','Pembuka botol',1,['gunting','playar','bottle opener','scissors'])],'Fulkrum ialah titik sokongan, beban ialah objek, daya digunakan untuk mengangkatnya.']
];
applications.forEach((a,i)=>SB.add('science',{id:'sc-a-'+i,topic:a[0],stem:a[1],en:a[2],diagram:{type:'science',kind:a[3]},parts:a[4],hints:['Cari fungsi setiap bahagian terlebih dahulu.','Gunakan istilah sains yang tepat.','Contoh lain: akar menyerap air, daun membuat makanan.'],explanation:a[5]}));
for(let set=1;set<=2;set++){const A=SB.banks.science.filter(q=>q.id.startsWith('sc-f-')).slice((set-1)*10,set*10);const B=SB.banks.science.filter(q=>q.id.startsWith('sc-a-')).slice((set-1)*2,set*2);const ids=set===1?[1,0,2,3]:[8,12,17,16];const C=ids.map(i=>{let q=SB.banks.science.find(q=>q.id==='sc-v-'+i);return{...q,id:'sc-ex-'+set+'-'+i};});SB.paper('science',set,[{name:'Bahagian A',instructions:'Jawab semua 10 soalan objektif. / Answer all 10 multiple-choice questions.',questions:A},{name:'Bahagian B',instructions:'Jawab 2 soalan pelbagai bentuk. / Answer both questions.',questions:B},{name:'Bahagian C',instructions:'Jawab 4 soalan penyiasatan berangkai. Gunakan data dan sebab saintifik. / Answer all 4 investigation questions.',questions:C}]);}
