SB.register('math',[
SB.topic('nombor','Nombor & operasi','Kenal nilai tempat. Untuk soalan cerita, tentukan operasi daripada maklumat yang diberi, bukan hanya kata kunci.','Contoh: 4 kotak berisi 12 buku setiap satu. Jumlah = 4 × 12 = 48 buku.'),
SB.topic('pecahan','Pecahan, perpuluhan & peratus','Pecahan ialah bahagian daripada keseluruhan. Pastikan jumlah keseluruhan tepat sebelum mencari peratus.','Contoh: 2 daripada 8 bahagian = 2/8 = 25%. Perpuluhan 0.25 mewakili kuantiti sama.'),
SB.topic('wang','Wang & pilihan jimat','Cari harga seunit dahulu untuk membanding tawaran. Kemudian darab dengan kuantiti yang diperlukan.','Contoh: 3 botol RM12 → RM4 sebotol. Lima botol = RM20.'),
SB.topic('masa','Masa & tempoh','Asingkan jam dan minit. 60 minit = 1 jam. Baca jadual sebelum menentukan masa mula dan tamat.','Contoh: 08:45 hingga 10:15 = 1 jam 30 minit.'),
SB.topic('ukuran','Panjang, jisim & isi padu cecair','Samakan unit sebelum tambah atau tolak. 1 kg = 1 000 g; 1 km = 1 000 m; 1 L = 1 000 ml.','Contoh: 2 kg 300 g + 700 g = 3 kg.'),
SB.topic('ruang','Bentuk, luas & isi padu','Luas segi empat tepat = panjang × lebar. Isi padu kuboid = panjang × lebar × tinggi. Bezakan cm, cm² dan cm³.','Contoh: Kuboid 4 × 3 × 2 mempunyai isi padu 24 cm³.'),
SB.topic('koordinat','Koordinat','Baca x dahulu (melintang), kemudian y (menegak). Titik terletak pada persilangan dua nilai itu.','Contoh: (3, 2) ialah 3 unit ke kanan dan 2 unit ke atas.'),
SB.topic('data','Carta & pengurusan data','Baca tajuk, label dan skala carta. Bagi bar yang belum lengkap, cari nilainya daripada jadual dahulu.','Contoh: 30 kurang daripada 80 ialah 50. Pada skala 10, bar berakhir di petak kelima.')]);
const M=SB;const steps=(label,...patterns)=>({label,patterns});
const names=['Aina','Haris','Mira','Danial','Sofea','Iman','Ravi','Lina','Zaki','Mei'];
const goods=['buku cerita','anak pokok','botol jus','pek roti','kad ucapan','bekas pensel','tiket sukan','kotak susu','beg hadiah','pek biskut'];
function mathQ(id,topic,stem,en,diagram,parts,hints,explanation){return M.add('math',{id,topic,stem,en,diagram,parts,hints,explanation});}
function buildMath(v,exam=false){let n=names[v%10],g=goods[v%10],k=3+v%5,t=2+v%4;const pre=exam?'mx':'mp';let out=[];const add=q=>{out.push(q);return q;};
add(mathQ(pre+v+'-groups','nombor',`Rajah menunjukkan kumpulan ${g}. Lengkapkan ayat matematik.`,`The diagram shows groups of items. Complete the mathematics sentence.`,{type:'groups',groups:k,each:t,kind:v%3},[M.num('Bilangan kumpulan / Number of groups',k),M.num('Bilangan setiap kumpulan / Number in each group',t),M.num('Jumlah / Total',k*t)],['Kenal pasti berapa kumpulan yang ditunjukkan.','Bilangan kumpulan × bilangan setiap kumpulan.','Contoh lain: 2 kumpulan, 3 setiap kumpulan → 2 × 3 = 6.'],`${k} kumpulan × ${t} setiap kumpulan = ${k*t}.`));
let a=24000+v*1703,b=13000+v*917,c=6000+v*311;
add(mathQ(pre+v+'-operations','nombor',`${n} menerima ${a.toLocaleString()} ${g} untuk program sekolah. Sebanyak ${b.toLocaleString()} lagi diterima. ${c.toLocaleString()} telah diagihkan. Hitung baki.`,`Calculate the number of items remaining after receiving two batches and distributing some.`,{type:'table',headers:['Perkara / Item','Bilangan / Number'],rows:[['Penerimaan pertama',a],['Penerimaan kedua',b],['Diagihkan',c]]},[M.num('Baki / Remaining',a+b-c,3,'',[steps('Jumlah diterima',`${a}+${b}`),steps('Tolak yang diagihkan',`${a+b}-${c}`,`${a}+${b}-${c}`)])],['Asingkan jumlah diterima daripada jumlah diagihkan.','Tambah dua penerimaan dahulu, kemudian tolak.','Contoh lain: 700 + 200 − 100 = 800.'],`${a} + ${b} = ${a+b}. Kemudian ${a+b} − ${c} = ${a+b-c}.`));
let l=5+v%6,w=3+v%4,h=2+v%3;
add(mathQ(pre+v+'-volume','ruang','Rajah menunjukkan sebuah kuboid. Hitung isi padu dalam cm³. Tunjukkan pengiraan.','The diagram shows a cuboid. Calculate its volume in cm³. Show your working.',{type:'cuboid',l,w,h},[M.num('Isi padu / Volume',l*w*h,3,'cm³',[steps('Panjang × lebar × tinggi',`${l}*${w}*${h}`,`${w}*${l}*${h}`,`${l*w}*${h}`)])],['Isi padu mengukur ruang di dalam bentuk 3D.','Gunakan panjang × lebar × tinggi.','Contoh lain: 4 cm × 2 cm × 3 cm = 24 cm³.'],`${l} × ${w} × ${h} = ${l*w*h} cm³. cm² ialah unit luas, bukan isi padu.`));
let den=8,num=2+v%5;
add(mathQ(pre+v+'-fraction','pecahan','Rajah dibahagi kepada bahagian sama besar. Nyatakan pecahan bahagian berlorek dalam bentuk termudah.','State the fraction of shaded parts in its simplest form.',{type:'fraction',total:den,shaded:num},[M.num('Pecahan / Fraction',num/den,1)],['Kira bahagian berlorek dan jumlah semua bahagian.','Tulis berlorek / jumlah. Bahagi pengangka dan penyebut dengan faktor sepunya.','Contoh lain: 3/6 = 1/2.'],`${num}/${den} mewakili bahagian berlorek. Pecahan setara diterima.`));
let hundred=(v%4+1)*25;
add(mathQ(pre+v+'-percent','pecahan','Jadual menunjukkan pilihan aktiviti murid. Hitung peratus murid yang memilih aktiviti pertama.','Calculate the percentage of pupils choosing the first activity.',{type:'table',headers:['Aktiviti / Activity','Murid / Pupils'],rows:[['Melukis',hundred/5],['Bermain',20-hundred/5]]},[M.num('Peratus / Percentage',hundred,3,'%',[steps('Bahagian ÷ keseluruhan × 100',`${hundred/5}/20*100`,`${hundred/5}/(20)*100`)])],['Jumlah murid termasuk kedua-dua aktiviti.','Bilangan aktiviti pertama ÷ jumlah × 100.','Contoh lain: 6 daripada 12 = 6 ÷ 12 × 100 = 50%.'],`${hundred/5} daripada 20 murid: ${hundred/5} ÷ 20 × 100 = ${hundred}%.`));
let x=1+v%5,y=2+v%4,vx=6-v%4,vy=1+v%5;
add(mathQ(pre+v+'-coordinates','koordinat',`Rajah menunjukkan titik P. (a) Tandakan titik Q pada (${vx}, ${vy}). (b) Nyatakan koordinat P.`,`Mark Q at (${vx}, ${vy}) and state the coordinates of P.`,{type:'coordinates',point:[x,y],label:'P'},[{type:'coordinate',label:'(a) Klik persilangan untuk Q / Click the intersection for Q',answer:[vx,vy],marks:1},M.text('(b) Koordinat P / Coordinates of P',`(${x}, ${y})`,1,[`${x},${y}`,`${x} ${y}`])],['x dibaca dahulu, kemudian y.','Gerak melintang dahulu sebelum menegak.','Contoh lain: (2, 4) → kanan 2, atas 4.'],`Q terletak pada (${vx}, ${vy}). P berada pada (${x}, ${y}).`));
let kg=2+v%4,gram=250+v%4*150,extra=1000-gram;
add(mathQ(pre+v+'-mass','ukuran',`${n} mempunyai ${kg} kg ${gram} g ${g}. Dia menambah ${extra} g lagi. Hitung jumlah jisim dalam kg.`,`Calculate the total mass in kg.`,{type:'mass',values:[`${kg} kg ${gram} g`,`${extra} g`]},[M.num('Jumlah jisim / Total mass',kg+1,3,'kg',[steps('Gabungkan gram',`${gram}+${extra}`,`${kg*1000+gram}+${extra}`)])],['1 kg bersamaan 1 000 g.','Tambah gram dahulu. Tukar setiap 1 000 g kepada 1 kg.','Contoh lain: 3 kg 600 g + 400 g = 4 kg.'],`${gram} g + ${extra} g = 1 000 g = 1 kg. Jumlah ${kg+1} kg.`));
let hr=8+v%4,mins=15+(v%3)*15,duration=75+v%3*15,end=hr*60+mins+duration;
add(mathQ(pre+v+'-time','masa',`Aktiviti bermula pada ${String(hr).padStart(2,'0')}:${mins}. Tempohnya ${duration} minit. Nyatakan masa tamat dalam sistem 24 jam.`,`The activity starts at ${String(hr).padStart(2,'0')}:${mins} and lasts ${duration} minutes. State its ending time.`,{type:'schedule',start:`${hr}:${mins}`,duration:`${duration} minit`},[M.text('Masa tamat / Ending time',`${String(Math.floor(end/60)).padStart(2,'0')}:${String(end%60).padStart(2,'0')}`,2,[`${Math.floor(end/60)}:${String(end%60).padStart(2,'0')}`,`${Math.floor(end/60)}.${String(end%60).padStart(2,'0')}`])],['60 minit membentuk satu jam.','Tambah jam penuh dahulu, kemudian baki minit.','Contoh lain: 09:50 + 20 minit = 10:10.'],`Masa tamat ialah ${Math.floor(end/60)}:${String(end%60).padStart(2,'0')}.`));
let price=4.5+v%5,budget=50+v*5,qty=3+v%4;
add(mathQ(pre+v+'-money','wang',`${n} membeli ${qty} ${g} pada harga RM${price.toFixed(2)} setiap satu. Dia membayar RM${budget}. Hitung baki wang.`,`Calculate the change after buying ${qty} items.`,{type:'price',item:g,price:price.toFixed(2),quantity:qty},[M.num('Baki wang / Change',+(budget-qty*price).toFixed(2),4,'RM',[steps('Kos semua barang',`${qty}*${price}`,`${price}*${qty}`),steps('Bayaran − kos',`${budget}-${qty*price}`)])],['Baki ialah wang dibayar tolak kos belian.','Cari jumlah kos dengan darab dahulu.','Contoh lain: 2 barang × RM3 = RM6; RM10 − RM6 = RM4.'],`Kos = ${qty} × RM${price.toFixed(2)} = RM${(qty*price).toFixed(2)}. Baki = RM${(budget-qty*price).toFixed(2)}.`));
let vals=[80+v%4*10,50+v%3*10,70+v%3*10,30+v%3*10];
add(mathQ(pre+v+'-chart','data','Lengkapkan carta palang bagi Memanah dan Mewarna berdasarkan jadual. Klik petak terakhir atau masukkan nilai.','Complete the bar chart for Archery and Colouring using the table.',{type:'bars',labels:['Senamrobik','Sukaneka','Memanah','Mewarna'],values:vals,missing:[2,3],max:140,step:10},[M.num('Memanah / Archery',vals[2],1),M.num('Mewarna / Colouring',vals[3],1)],['Baca skala: satu petak mewakili 10 peserta.','Cari nilai aktiviti yang belum mempunyai bar.','Contoh lain: 60 peserta → enam petak jika satu petak = 10.'],`Memanah ${vals[2]}, mewarna ${vals[3]}. Kedua-dua bar mesti mengikut skala carta.`));
let p=7+v%5,q=4+v%3;
add(mathQ(pre+v+'-area','ruang','Hitung luas segi empat tepat dalam rajah.','Calculate the area of the rectangle.',{type:'rectangle',l:p,w:q},[M.num('Luas / Area',p*q,3,'cm²',[steps('Panjang × lebar',`${p}*${q}`,`${q}*${p}`)])],['Luas mengukur permukaan, bukan panjang keliling.','Gunakan panjang × lebar.','Contoh lain: 5 cm × 2 cm = 10 cm².'],`Luas = ${p} × ${q} = ${p*q} cm².`));
let path=+(5.25+v*.25).toFixed(2),back1=+(2.4+v*.1).toFixed(2),back2=+(3.2+v*.2).toFixed(2);
add(mathQ(pre+v+'-route','ukuran',`${n} pergi dari rumah ke perpustakaan melalui sekolah, dan pulang melalui taman. Nyatakan jarak pergi dan jumlah jarak perjalanan.`,`State the outgoing distance and total distance travelled.`,{type:'route',labels:['Rumah','Sekolah','Perpustakaan','Taman'],distances:[path,back1,back2]},[M.num('(i) Jarak pergi / Outgoing distance',path,2,'km'),M.num('(ii) Jumlah jarak / Total distance',+(path+back1+back2).toFixed(2),3,'km',[steps('Jumlah laluan pergi dan pulang',`${path}+${back1}+${back2}`,`${back1}+${back2}+${path}`)])],['Perhatikan laluan pergi dan laluan pulang yang berbeza.','Tambah semua jarak yang dilalui sekali sahaja.','Contoh lain: pergi 4 km, pulang 2 km + 3 km → jumlah 9 km.'],`Pergi ${path} km. Jumlah = ${path} + ${back1} + ${back2} = ${(path+back1+back2).toFixed(2)} km.`));
let decimal=+(1.25+v*.25).toFixed(2),addDec=+(2.5+v*.15).toFixed(2);
add(mathQ(pre+v+'-decimal','pecahan',`${n} menggunakan ${decimal} m reben biru dan ${addDec} m reben merah. Hitung jumlah panjang.`,`Calculate the total ribbon length.`,{type:'table',headers:['Warna / Colour','Panjang / Length'],rows:[['Biru / Blue',decimal+' m'],['Merah / Red',addDec+' m']]},[M.num('Jumlah panjang / Total length',+(decimal+addDec).toFixed(2),3,'m',[steps('Tambah dua panjang',`${decimal}+${addDec}`,`${addDec}+${decimal}`)])],['Susun titik perpuluhan pada kedudukan yang sama.','Tambah nilai setiap tempat dari kanan.','Contoh lain: 1.20 + 2.35 = 3.55 m.'],`${decimal} + ${addDec} = ${(decimal+addDec).toFixed(2)} m.`));
return out;}
// 156 situasi latihan, 13 bentuk item; perubahan merangkumi jenis bahan, konteks dan data.
for(let v=0;v<12;v++)buildMath(v);
function mathLong(set,which){let variant=set===1?0:1;if(which===0){const cost=variant?7:6,pack=variant?4:3,pcost=variant?24:15,amount=variant?8:9,budget=variant?80:70;let cheaper=pcost/pack;
return mathQ('mx-long-'+set+'-shop','wang',set===1?'Kelab Seni membeli 9 pek warna untuk bengkel. Bandingkan dua tawaran dan rancang belian.':'Kelab Sukan membeli 8 pek tuala untuk kejohanan. Tentukan tawaran terbaik dan baki peruntukan.','Compare the offers and plan the purchase.',{type:'offers',items:[{name:'Kedai Seri',quantity:1,price:cost},{name:'Kedai Maju',quantity:pack,price:pcost}],item:set===1?'Pek warna':'Pek tuala'},[M.num('(i) Harga seunit di Kedai Maju / Unit price',cheaper,3,'RM',[steps('Harga pek ÷ bilangan',`${pcost}/${pack}`)]),M.num('(ii) Kos membeli '+amount+' pek di Kedai Maju / Total cost',amount*cheaper,3,'RM',[steps('Bilangan × harga seunit',`${amount}*${cheaper}`,`${cheaper}*${amount}`)]),M.num('(iii) Baki daripada RM'+budget+' / Remaining budget',budget-amount*cheaper,3,'RM',[steps('Bajet − kos',`${budget}-${amount*cheaper}`)]),M.concept('(iv) Kedai manakah paling jimat? Berikan sebab berdasarkan harga. / Which shop is cheaper? Give a reason.','Kedai Maju kerana harga seunit lebih rendah.',[['maju'],['lebih murah','lebih rendah','cheaper','lower']],3)],['Bandingkan kuantiti yang sama.','Harga seunit = harga tawaran ÷ bilangan barang.','Contoh lain: 2 pek RM8 ialah RM4 setiap pek; 1 pek RM5 lebih mahal.'],`Kedai Maju RM${cheaper.toFixed(2)} seunit; kos RM${amount*cheaper}; baki RM${budget-amount*cheaper}.`);
}let go=variant?7.5:6.25,via=variant?3.75:2.5,last=variant?4.25:3.25,litres=variant?2:3,used=variant?650:450;
return mathQ('mx-long-'+set+'-trip','ukuran',set===1?'Murid menyertai lawatan ke pusat sains. Bas pergi melalui sekolah dan pulang melalui taman. Mereka menyediakan air minuman untuk perjalanan.':'Pasukan sekolah ke stadium. Van pergi melalui perpustakaan dan pulang melalui taman. Mereka membawa bekalan air untuk latihan.','Read the route map and solve the linked travel problems.',{type:'route',labels:['Rumah',variant?'Perpustakaan':'Sekolah',variant?'Stadium':'Pusat sains','Taman'],distances:[go,via,last]},[M.num('(i) Jarak pergi / Outgoing distance',go,2,'km'),M.num('(ii) Jumlah jarak / Total distance',go+via+last,4,'km',[steps('Jumlah jarak pulang',`${via}+${last}`),steps('Pergi + pulang',`${go}+${via+last}`,`${go}+${via}+${last}`)]),M.num('(iii) Baki air selepas menggunakan '+used+' ml daripada '+litres+' L / Water remaining',litres*1000-used,4,'ml',[steps('Tukar L kepada ml',`${litres}*1000`),steps('Bekalan − digunakan',`${litres*1000}-${used}`)]),M.text('(iv) Nyatakan satu sebab bas tidak melalui jalan yang sama semasa pulang. / Give one possible reason.','Mengelakkan kesesakan',2,['jalan ditutup','mengelakkan jalan sesak','avoid traffic','road closed'])],['Setiap bahagian menggunakan maklumat yang berbeza.','Untuk air, samakan unit kepada ml dahulu.','Contoh lain: 2 L − 300 ml = 2 000 ml − 300 ml = 1 700 ml.'],`Jumlah perjalanan = ${go+via+last} km. Baki air = ${litres*1000-used} ml. Jawapan sebab lain yang munasabah perlu semakan ibu bapa.`);}
for(let set=1;set<=2;set++){let qs=buildMath(15+set,true);const wanted=[0,1,2,3,4,5,6,7,8,9,10,11,12];let small=qs.map(q=>({...q,parts:q.parts.map(p=>({...p,steps:[]}))}));
// Agihan A: 26 markah, B: 24 markah. Setiap A menyokong respons terhad.
small=small.map(q=>{let parts=q.parts.map(p=>({...p}));if(q.diagram.type==='groups'){parts=[M.num('Bilangan kumpulan',q.parts[0].answer,1),M.num('Bilangan setiap kumpulan',q.parts[1].answer,1),M.num('Jumlah',q.parts[2].answer,1)];}
else if(q.diagram.type==='coordinates'||q.diagram.type==='bars'){parts=q.parts.map(p=>({...p,marks:1}));}
else if(q.topic==='ukuran'&&q.diagram.type==='route'){parts=[{...q.parts[0],marks:1,unit:'',steps:[]},{...q.parts[1],marks:1,unit:'',steps:[]}];}
else{const old=q.parts[0];parts=[{...old,marks:q.diagram.type==='fraction'?1:2,steps:[],unit:old.unit}];}
return{...q,parts,marks:parts.reduce((a,p)=>a+p.marks,0)};});
M.paper('math',set,[{name:'Bahagian A',instructions:'Jawab semua 13 soalan. Lengkapkan jawapan, rajah atau carta seperti yang diarahkan. / Answer all 13 questions.',questions:small},{name:'Bahagian B',instructions:'Jawab kedua-dua soalan berangkai. Tunjukkan langkah pengiraan. / Answer both structured questions. Show your working.',questions:[mathLong(set,0),mathLong(set,1)]}]);}
