/* Tambahan bentuk respons dan topik yang memerlukan sesi lengkap. */
const allQuestions=[...Object.values(SB.banks).flat(),...Object.values(SB.papers).flatMap(p=>p.questions)];
for(const q of allQuestions){if(q.id==='bm-write-0'){q.stem='Berdasarkan grafik, berikan pendapat tentang amalan hidup berjiran. Tulis satu perenggan tidak melebihi 50 patah perkataan.';q.parts[0].keywords=[['sapa','menyapa','bertegur','salam'],['makanan','kongsi','berkongsi'],['ziarah','menziarahi','sakit','prihatin']];}if(q.id.startsWith('english-r-')&&String(q.parts[0].answer).includes(' and '))q.parts[0].groups=String(q.parts[0].answer).split(' and ').map(s=>[s.trim()]);}
for(const q of allQuestions){if(q.id==='en-write-0'){q.stem='Your friend has a sore throat and a fever. What advice will you give your friend? Give TWO reasons. Write 40–50 words in one paragraph.';q.parts[0].keywords=[['advice','should','friend'],['water','drink'],['nurse','sick bay','rest'],['because','so','reason']];}if(q.id==='en-write-1'){q.title='Making pizza with your aunt';q.stem='Your aunt invites you to learn how to make pizza at her house this weekend. Do you want to join? Give TWO reasons. Write 40–50 words in one paragraph.';q.parts[0].keywords=[['join','yes','no','would'],['pizza','cook','make'],['learn','skill','fun','aunt'],['because','so','reason']];}if(q.id==='bm-write-1')q.parts[0].keywords=[['basuh','mencuci tangan'],['gigi','memberus'],['pakaian','bersih','kemas']];if(q.id==='bm-write-2'){q.title='Sayangi buku teks';q.stem='Berdasarkan grafik, nyatakan dua cara menjaga kebersihan dan keselamatan buku teks. Tulis satu perenggan tidak melebihi 50 patah perkataan.';q.parts[0].keywords=[['balut','membalut','sampul'],['buku'],['simpan','beg','jaga','menjaga']];}if(q.id==='bm-write-5')q.parts[0].keywords=[['suis','matikan'],['basah','kering'],['palam','cabut','tanggalkan'],['selamat','berhati-hati']];}
for(let set=1;set<=2;set++){let C=SB.papers['science-'+set].questions.filter(q=>q.section==='Bahagian C');C.forEach((q,pos)=>{const i=Number(q.id.split('-').pop()),exp=SB.experiments[i],skill=n=>structuredClone(SB.banks.science.find(x=>x.id==='sc-k-'+i+'-'+n).parts[0]),v=q.parts.map(p=>structuredClone(p));q.topic=exp[1];q.en='Read the investigation and its results. Answer each question using the data and scientific concepts.';q.parts=pos===0?[v[0],v[1],skill(0),v[3]]:pos===1?[skill(1),v[2],skill(3),v[3]]:pos===2?[skill(0),v[1],skill(3),v[3]]:[skill(1),v[0],v[2],skill(3)];q.parts.forEach((p,j)=>p.label='('+String.fromCharCode(97+j)+') '+p.label.replace(/^\([a-d]\) /,''));q.explanation='Jawab setiap perkara yang diminta: fakta data, tujuan, hubungan atau sebab saintifik. '+exp[6];});}
[
['perenggan','Kebun sekolah','garden','cara menjaga kebun sekolah',[['tanam'],['siram'],['bersih','rumput']]],
['perenggan','Sudut bacaan','books','cara menjaga sudut bacaan',[['buku'],['susun'],['baca','bersih']]],
['perenggan','Kitar semula','recycle','kegunaan semula bahan dalam grafik',[['botol'],['kotak'],['kitar','guna semula']]],
['perenggan','Sukan sekolah','sports','manfaat aktiviti sukan dalam grafik',[['sukan','bola'],['sihat','cergas'],['rakan','kerjasama']]],
['karangan','Aktiviti berkebun','garden','aktiviti berkebun bersama rakan di sekolah',[['sekolah','rakan'],['tanam'],['siram'],['gembira','kerjasama']]],
['karangan','Lawatan perpustakaan','books','pengalaman mengunjungi perpustakaan',[['perpustakaan'],['buku'],['baca','meminjam'],['ilmu','gembira']]],
['karangan','Projek kelas lestari','recycle','aktiviti kitar semula di kelas',[['kelas','rakan'],['botol','kotak'],['kitar','guna semula'],['bersih','alam']]],
['karangan','Bermain bersama rakan','sports','pengalaman bersukan bersama rakan',[['rakan','padang'],['bola','sukan'],['sihat','cergas'],['gembira','kerjasama']]]
].forEach((w,i)=>SB.add('bm',{id:'bm-extra-write-'+i,topic:w[0],title:w[1],stem:'Berdasarkan bahan grafik, huraikan '+w[3]+'. Tulis '+(w[0]==='karangan'?'karangan 80–100 patah perkataan.':'satu perenggan tidak melebihi 50 patah perkataan.'),diagram:{type:'scene',kind:w[2],title:w[1]},parts:[SB.essay('Tulis jawapan kamu.',w[0]==='karangan'?80:1,w[0]==='karangan'?100:50,w[4],w[0]==='karangan'?20:10,w[0]==='karangan'?[8,6,4,2]:[4,3,2,1])],hints:['Perhatikan objek, tempat dan perbuatan dalam grafik.','Pilih tiga isi berkaitan dan susun secara teratur.','Contoh topik lain: memasak dimulakan dengan persediaan, langkah kerja dan hasil.'],explanation:'Jawapan berbeza boleh diterima. Semak isi, bahasa, susunan dan ejaan bersama ibu bapa.'}));
const extraScience=[
['tenaga','Lampu suluh menggunakan bateri. Nyatakan perubahan tenaga sehingga lampu menyala.','State the energy changes in a battery-powered torch.','circuit','Kimia → elektrik → cahaya',[['kimia','chemical'],['elektrik','electrical'],['cahaya','light']]],
['tenaga','Kipas yang disambungkan kepada soket berpusing. Apakah perubahan tenaga utama?','State the main energy change in a running fan.','fan','Elektrik → kinetik',[['elektrik','electrical'],['kinetik','kinetic','pergerakan']]],
['tenaga','Mengapakah kita perlu mematikan lampu apabila bilik tidak digunakan?','Why switch off lights in an empty room?','circuit','Menjimatkan tenaga dan mengelakkan pembaziran.',[['jimat','save'],['tenaga','elektrik','energy','electricity']]],
['tenaga','Nyatakan sumber tenaga bagi fotosintesis dan bagi kipas elektrik.','Name the energy sources for photosynthesis and an electric fan.','plants','Matahari; bekalan elektrik',[['matahari','sun'],['elektrik','electricity']]],
['bumi','Bahagian Bumi yang menghadap Matahari mengalami apakah keadaan? Terangkan.','What happens on the side of Earth facing the Sun? Explain.','earth','Siang kerana menerima cahaya Matahari.',[['siang','day'],['cahaya','light','matahari','sun']]],
['bumi','Mengapakah siang dan malam berlaku secara bergilir-gilir?','Why do day and night alternate?','earth','Bumi berputar pada paksinya.',[['bumi','earth'],['putar','rotate','rotation']]],
['bumi','Nyatakan daya yang menyebabkan bola yang dilepaskan jatuh ke tanah.','Name the force causing a released ball to fall.','gravity','Daya graviti Bumi.',[['graviti','gravity']]],
['bumi','Apakah dua jenis pergerakan Bumi?','Name the two movements of Earth.','earth','Putaran pada paksi dan peredaran mengelilingi Matahari.',[['putaran','berputar','rotation'],['peredaran','mengelilingi matahari','revolution','revolves']]],
['bumi','Mengapakah kita tidak boleh melihat Matahari pada waktu malam di tempat kita?','Why can we not see the Sun at night in our location?','earth','Bahagian Bumi di tempat kita membelakangi Matahari.',[['membelakangi','tidak menghadap','away'],['matahari','sun']]],
['mesin','Apakah kegunaan satah condong ketika menaikkan kotak ke atas lori?','How does an inclined plane help move a box onto a lorry?','ramp','Memudahkan menaikkan kotak dengan daya lebih kecil.',[['memudahkan','mudah','easier'],['daya','force','tolak']]],
['mesin','Nyatakan mesin ringkas pada mata pisau dan kegunaannya.','Name the simple machine in a knife blade and its use.','wedge','Baji digunakan untuk memotong.',[['baji','wedge'],['potong','cut']]],
['mesin','Nyatakan mesin ringkas untuk menaikkan bendera pada tiang.','Name the simple machine used to raise a flag.','pulley','Takal.',[['takal','pulley']]]
];
extraScience.forEach((x,i)=>SB.add('science',{id:'sc-extra-'+i,topic:x[0],stem:x[1],en:x[2],diagram:{type:'science',kind:x[3]},parts:[SB.concept('Jawapan / Answer',x[4],x[5],2)],hints:['Kenal pasti alat atau fenomena yang ditanya.','Hubungkan fungsi alat dengan konsep sains.','Contoh lain: makanan membekalkan tenaga kepada manusia untuk bergerak.'],explanation:x[4]+' Frasa setara boleh diterima selepas semakan.'}));
for(let set=1;set<=2;set++){const q=SB.papers['bm-'+set].questions.find(q=>q.id==='bm-ex-b-'+set);q.parts[0]=set===1?SB.concept('(a) Di manakah Haris menemukan dompet?','Di bawah meja.',[['bawah meja']],2):SB.concept('(a) Siapakah jiran yang dibantu keluarga Iman?','Pak Zain.',[['pak zain','zain']],2);q.parts[3]=set===1?SB.text('(d) Cari satu kata kerja dalam petikan.','menyusun',2,['menemukan','menyerahkannya','membuat','mengambilnya','meminjam','membuka','datang','pergi','mengambil']):SB.text('(d) Cari satu kata kerja dalam petikan.','mengangkat',2,['membantu','menyusun','membawa','menyediakan','bekerjasama','belajar','berpindah']);}
for(const set of [1,2]){let q=SB.papers['math-'+set].questions.find(q=>q.id.endsWith('-volume'));let original=SB.banks.math.find(x=>x.id===q.id);q.parts[0].steps=original.parts[0].steps;}
const second=SB.papers['math-2'].questions;
const change=(suffix,stem,en,diagram,parts,explanation)=>{let q=second.find(q=>q.id.endsWith(suffix));Object.assign(q,{stem,en,diagram,parts,explanation,marks:parts.reduce((a,p)=>a+p.marks,0)});};
change('-operations','Pusat cetakan menghasilkan 18 450 risalah. 6 275 diagihkan pada pagi dan 4 890 pada petang. Hitung baki.','Calculate the leaflets remaining.',{type:'table',headers:['Perkara','Bilangan'],rows:[['Dicetak',18450],['Pagi',6275],['Petang',4890]]},[SB.num('Baki risalah',7285,2,'',[{label:'Tolak kedua-dua agihan',patterns:['18450-6275-4890','18450-11165']}])],'18 450 − 6 275 − 4 890 = 7 285.');
change('-percent','40 murid memilih aktiviti. 30% memilih melukis. Hitung bilangan murid yang memilih melukis.','30% of 40 pupils choose drawing. How many pupils is that?',{type:'table',headers:['Aktiviti','Peratus'],rows:[['Melukis','30%'],['Lain-lain','70%']]},[SB.num('Bilangan murid',12,2,'',[{label:'Peratus × keseluruhan',patterns:['30/100*40','0.3*40','40*0.3','40*30/100']}])],'30 ÷ 100 × 40 = 12 murid.');
change('-mass','3 kg 450 g botol plastik dikumpulkan. Sebanyak 875 g dihantar ke pusat kitar semula. Hitung baki jisim dalam g.','Calculate the mass remaining in grams.',{type:'mass',values:['3 kg 450 g','875 g dihantar']},[SB.num('Baki jisim',2575,2,'g')],'3 450 − 875 = 2 575 g.');
change('-time','Bas bertolak pada 09:45 dan tiba pada 11:20. Hitung tempoh perjalanan dalam minit.','Calculate the journey duration in minutes.',{type:'schedule',start:'09:45 → 11:20',duration:'Cari tempoh'},[SB.num('Tempoh',95,2,'minit')],'60 minit + 35 minit = 95 minit.');
change('-area','Hitung perimeter segi empat tepat dalam rajah, bukan luas.','Calculate the perimeter of the rectangle.',{type:'rectangle',l:12,w:7},[SB.num('Perimeter',38,2,'cm')],'12 + 7 + 12 + 7 = 38 cm.');
change('-decimal','Ibu mempunyai 6.50 m reben. Dia menggunakan 2.75 m. Hitung baki panjang.','Calculate the ribbon length remaining.',{type:'table',headers:['Reben','Panjang'],rows:[['Asal','6.50 m'],['Digunakan','2.75 m']]},[SB.num('Baki panjang',3.75,2,'m')],'6.50 − 2.75 = 3.75 m.');
for(const set of [1,2]){const trip=SB.papers['math-'+set].questions.find(q=>q.id==='mx-long-'+set+'-trip');trip.parts[3]=SB.concept('(iv) Berikan satu sebab munasabah laluan pulang berbeza. / Give one possible reason for a different return route.','Mengelakkan kesesakan atau jalan ditutup.',[['sesak','kesesakan','ditutup','traffic','closed','singgah','hantar','ambil','shorter','lebih dekat','lebih pendek']],2);}
for(const q of second.slice(0,13).filter(q=>['-operations','-percent','-mass','-time','-area','-decimal'].some(s=>q.id.endsWith(s)))){SB.add('math',{...structuredClone(q),id:'mp-new-'+q.id,section:undefined,number:undefined,hints:['Baca apa yang perlu dicari, bukan pilih operasi berdasarkan kata kunci sahaja.','Bandingkan unit dan kuantiti yang diberi sebelum mengira.','Contoh lain: 12 barang, 4 diagihkan → baki 8.'],explanation:q.explanation});}
// Buang pendua matematik yang hanya berlainan nama tetapi rajah, data dan tugasan sama.
const seenMath=new Set();SB.banks.math=SB.banks.math.filter(q=>{if(q.id.startsWith('mx'))return true;let signature=JSON.stringify([q.diagram,q.parts]);if(seenMath.has(signature))return false;seenMath.add(signature);return true;});
const bmDistractors=[
[['Isnin','Rabu','Selasa'],['Kelab Bahasa Melayu','Kelab Sains','Kelab Sukan'],['di dalam stor','di tengah padang','di belakang dewan'],['supaya pokok tidak perlu disiram','supaya alatan tidak perlu disimpan','supaya murid dapat bekerja seorang diri']],
[['Selasa','Sabtu','Ahad'],['pukul sembilan','pukul tujuh','pukul sepuluh'],['di papan kenyataan','di komputer','di buku teks'],['supaya dapat membeli hadiah','supaya dapat bermain di luar muzium','supaya boleh berlari di dalam muzium']]];
for(let set=1;set<=2;set++){let paper=SB.papers['bm-'+set];paper.questions.filter(q=>q.section==='Bahagian A'&&q.id.startsWith('bm-r-')).forEach((q,i)=>q.parts[0].options=[q.parts[0].options[0],...bmDistractors[set-1][i]]);
let en=SB.papers['english-'+set];let replacements=[];for(let j=0;j<3;j++){let i=(set-1)*3+j,source=SB.banks.english.find(q=>q.id==='english-p-'+i+'-'+j),answer=source.parts[0].answer,wrong=j===0?['12 November','18 December','24 September']:j===1?['Library','School hall','Science centre'].filter(s=>s!==answer).concat(['Classroom']).slice(0,3):['RM4','RM6','RM8'];let q=structuredClone(source);q.parts=[SB.mcq('Read the short text and choose the best answer.',[answer,...wrong],0,2)];q.marks=2;q.section='Part 2';q.number=j+1;replacements.push(q);}let pos=0;en.questions=en.questions.map(q=>q.section==='Part 2'?replacements[pos++]:q);}
